TEAM_ALIASES: dict[str, list[str]] = {
    "Inter": ["Internazionale", "Inter Milan"],
    "Milan": ["AC Milan"],
    "Juventus": ["Juve"],
    "Roma": ["AS Roma"],
    "Napoli": ["SSC Napoli"],
    "Real Madrid": ["Real"],
    "Barcelona": ["Barcellona", "FC Barcelona"],
    "Manchester City": ["Man City", "City"],
    "Manchester United": ["Man United", "Man Utd"],
    "Algeria": ["Algerien"],
    "Argentina": ["Albiceleste", "Argentinien"],
    "Australia": ["Australien"],
    "Austria": ["Oesterreich", "Osterreich"],
    "Belgium": ["Belgio", "Belgien"],
    "Bosnia and Herzegovina": ["Bosnia ed Erzegovina", "Bosnia", "Bosnien und Herzegowina"],
    "Brazil": ["Brasile", "Brasilien"],
    "Canada": ["Kanada"],
    "Cape Verde": ["Capo Verde", "Kap Verde"],
    "Chile": ["Cile"],
    "Colombia": ["Kolumbien"],
    "Costa Rica": [],
    "Croatia": ["Croazia", "Kroatien"],
    "Curacao": ["Curaçao"],
    "Czech Republic": ["Repubblica Ceca", "Cechia", "Tschechien"],
    "DR Congo": ["RD Congo", "DR Kongo", "Repubblica Democratica del Congo", "Congo DR"],
    "Ecuador": [],
    "Egypt": ["Egitto", "Aegypten"],
    "England": ["Inghilterra"],
    "France": ["Francia", "Frankreich"],
    "Germany": ["Germania", "Deutschland"],
    "Ghana": [],
    "Haiti": [],
    "Iran": [],
    "Iraq": ["Irak"],
    "Italy": ["Italia", "Italien"],
    "Ivory Coast": ["Costa d'Avorio", "Elfenbeinkueste", "Elfenbeinkuste"],
    "Japan": ["Giappone"],
    "Jordan": ["Giordania", "Jordanien"],
    "Mexico": ["Messico", "Mexiko"],
    "Morocco": ["Marocco", "Marokko"],
    "Netherlands": ["Paesi Bassi", "Olanda", "Niederlande"],
    "New Zealand": ["Nuova Zelanda", "Neuseeland"],
    "Nigeria": [],
    "Norway": ["Norvegia", "Norwegen"],
    "Panama": [],
    "Paraguay": [],
    "Poland": ["Polonia", "Polen"],
    "Portugal": ["Portogallo"],
    "Qatar": ["Katar"],
    "Saudi Arabia": ["Arabia Saudita", "Saudi Arabien"],
    "Scotland": ["Scozia", "Schottland"],
    "Senegal": [],
    "Serbia": ["Serbien"],
    "South Africa": ["Sudafrica", "Sud Africa", "Suedafrika", "Sudafrika"],
    "South Korea": ["Corea del Sud", "Korea del Sud", "Suedkorea", "Sudkorea"],
    "Spain": ["Spagna", "Spanien"],
    "Sweden": ["Svezia", "Schweden"],
    "Switzerland": ["Svizzera", "Schweiz"],
    "Tunisia": ["Tunesien"],
    "Turkey": ["Turchia", "Turkiye", "Tuerkei", "Turkei"],
    "Ukraine": ["Ucraina"],
    "United States": ["USA", "Stati Uniti", "Vereinigte Staaten"],
    "Uruguay": [],
    "Uzbekistan": ["Usbekistan"],
    "Wales": ["Galles"],
}


def aliases_for(team_name: str) -> list[str]:
    values = [team_name]
    values.extend(TEAM_ALIASES.get(team_name, []))
    normalized = team_name.lower()
    for canonical, aliases in TEAM_ALIASES.items():
        alias_values = [canonical, *aliases]
        if any(normalized == alias.lower() for alias in alias_values):
            values.extend(alias_values)
    return sorted(set(values))
